### ISSUE TITLE
Azure Appservices are not capable of stream logs 

### ISSUE THREAD

**Issue by Wesam18** [pauldambra/Serilog.Sinks.Network#8]
Use case:

Deploy any application that uses Serilog.Sinks.network to Azure Appservices. You will notice that the application is not streaming any log and throw "Error: An address incompatible with the requested protocol was used " exception.

**Comment by pauldambra** [comment]
Looks straightforward. Will double check tonight... 

Turns out I've misconfigured appveyor so looks like the job that built your PR has also published to nuget (D'oh!). Feel free to grab that build and test on my behalf. And I'll have a word with past me about testing the AppVeyor build more thoroughly
